### PR TITLE
LMS-BHC-PR-34-Updated the checkFixBook method

### PR DESCRIPTION
**Pull request by ChelakaFernando**
LMS-BHC-PR-34-Updated the checkFixBook method

### CODE REVIEW

**Comment by ChelakaFernando** [comment]
@NiharikaGavvala The update is ready to review.Please ask @harshadilupkumara to review.

**Comment by NiharikaGavvala** [comment]
@harshadilupkumara can you please review the update that chelaka has done.

**Review by harshadilupkumara — COMMENTED** [review]
@NiharikaGavvala  Approved
Ask Chelaka to commit the changes to the master branch

**Review by harshadilupkumara — APPROVED** [review]
@NiharikaGavvala  Approved
Ask Chelaka to commit the changes to the master branch

**Comment by NiharikaGavvala** [comment]
@ChelakaFernando harsha has approved it and you are ready to merge to the master branch.

**Comment by ChelakaFernando** [comment]
The checkFixBook method is merging to master

**Pull request merged**
