### PR TITLE
LMS-NG-PR-119-Refactored main class

### PR DESCRIPTION
**Pull request by NiharikaGavvala**
@harshadilupkumara can you please ask chelaka to review the changes that have been done to main.java.

### CODE REVIEW

**Comment by harshadilupkumara** [comment]
@NiharikaGavvala 
Please review the file

**Review by ChelakaFernando — COMMENTED** [review]
please change the method name getMenu and payFines

**Review by ChelakaFernando — APPROVED** [review]
Approved.Ready to merge.

**Comment by ChelakaFernando** [comment]
@harshadilupkumara please tell @NiharikaGavvala to merge.

**Comment by harshadilupkumara** [comment]
@ChelakaFernando 
Please review the changes

**Comment by ChelakaFernando** [comment]
@harshadilupkumara its ready to merge

**Comment by harshadilupkumara** [comment]
@NiharikaGavvala 
Please merge the changes to the master branch

**Pull request merged**
