### PR TITLE
LMS-NG-PR-50-methods changed in main.java

### PR DESCRIPTION
**Pull request by NiharikaGavvala**
@harshadilupkumara can you please ask chelaka to review the changes made in main.java.

### CODE REVIEW

**Comment by harshadilupkumara** [comment]
@ChelakaFernando 
Please do the review on the changes

**Review by ChelakaFernando — COMMENTED** [review]
Please change payFineControl to PayFineControl in line 185

**Comment by NiharikaGavvala** [comment]
@harshadilupkumara can you ask chelaka to review the change please.

**Comment by harshadilupkumara** [comment]
@ChelakaFernando 
Niharika has done the changes please review the changes

**Review by ChelakaFernando — APPROVED** [review]
Approved.You can merge it now

**Pull request merged**
