### PR TITLE
LMS-NG-93-updated the author in member.java

### PR DESCRIPTION
**Pull request by NiharikaGavvala**
@ChelakaFernando can you please ask harsha to review this.

### CODE REVIEW

**Comment by ChelakaFernando** [comment]
@harshadilupkumara The update is ready to review.

Thanks

**Comment by ChelakaFernando** [comment]
@harshadilupkumara The update is ready to review.

Thanks

**Review by harshadilupkumara — APPROVED** [review]
@ChelakaFernando Approved,
Ask @NiharikaGavvala to commit the changes to master branch

**Comment by ChelakaFernando** [comment]
@NiharikaGavvala Harsha had approved.You can merge it now.

Thanks

**Pull request merged**
