### PR TITLE
LMS-BHC-PR-40-Updated setUi method

### PR DESCRIPTION
**Pull request by ChelakaFernando**
LMS-BHC-PR-40-Updated setUi method

### CODE REVIEW

**Comment by ChelakaFernando** [comment]
@harshadilupkumara Its ready to review.Please ask @NiharikaGavvala .
Thanks

**Comment by harshadilupkumara** [comment]
@NiharikaGavvala 
Please review the changes

**Review by NiharikaGavvala — APPROVED** [review]
@harshadilupkumara It has been approved and ask chelaka to merge it. Thanks.

**Comment by harshadilupkumara** [comment]
@ChelakaFernando 
Merge the changes to the master

**Pull request merged**
