### PR TITLE
LMS-BHC-PR-32-Updated scanBook method in FixBookControl.java

### PR DESCRIPTION
**Pull request by ChelakaFernando**
LMS-BHC-PR-32-Updated scanBook method in FixBookControl.java

### CODE REVIEW

**Comment by ChelakaFernando** [comment]
@NiharikaGavvala I have updated the scanBook method in FixBookControl class.Please ask harsha to review it.

Thanks.

**Comment by NiharikaGavvala** [comment]
@harshadilupkumara can you please review the scanBook method in FixBookControl class which chelaka has updated. Thank you.

**Review by harshadilupkumara — APPROVED** [review]
@NiharikaGavvala  Approved ask @ChelakaFernando to commit the changes to the master branch

**Comment by ChelakaFernando** [comment]
LMS-BHC-PR-32-Updated scanBook method in FixBookControl.java merging to master

**Pull request merged**
