### PR TITLE
LMS-BHC-PR-32-Updated the instance variables,Contructor,setUi,setScanningComplete methods

### PR DESCRIPTION
**Pull request by ChelakaFernando**
LMS-BHC-PR-32-Updated the instance variables,Contructor,setUi,setScanningComplete methods

### CODE REVIEW

**Comment by ChelakaFernando** [comment]
@NiharikaGavvala Plese ask harsha to review the update.

Thanks.

**Comment by NiharikaGavvala** [comment]
@harshadilupkumara can you please review chelaka's code. Thanks.

**Review by harshadilupkumara — APPROVED** [review]
@NiharikaGavvala Approved 
Asked Chelka to merge the changes

**Comment by NiharikaGavvala** [comment]
@ChelakaFernando can you please merge the code as harsha approved it. Thank you.

**Pull request merged**
