### PR TITLE
LMS-BHC-PR-36-Update the variable names according to the code style guidelines

### PR DESCRIPTION
**Pull request by ChelakaFernando**
LMS-BHC-PR-36-Update the variable names according to the code style guidelines

### CODE REVIEW

**Comment by ChelakaFernando** [comment]
@harshadilupkumara The update is ready to review.
Thanks

**Review by NiharikaGavvala — APPROVED** [review]
@harshadilupkumara It has been approved and ask chelaka to merge it to master. Thank you

**Comment by harshadilupkumara** [comment]
@NiharikaGavvala 
Chelaka has done some changes  please review it

**Comment by harshadilupkumara** [comment]
@ChelakaFernando 
Neharika Approve, ready to merge

**Comment by ChelakaFernando** [comment]
LMS-BHC-PR-36-Update the variable names according to the code style guidelines
Merging to master

**Pull request merged**
