### PR TITLE
LMS-BHC-PR-10-Updated the Return method according to code style guidelines in Book.java

### PR DESCRIPTION
**Pull request by ChelakaFernando**
LMS-BHC-PR-10-Updated the Return method according to code style guidelines in Book.java
Chelaka

### CODE REVIEW

**Comment by NiharikaGavvala** [comment]
@harshadilupkumara 
Hi, Chelaka has updated the return method in book.java. Can you Please review it.

**Comment by harshadilupkumara** [comment]
Ok, I will review it and let you know.

**Review by harshadilupkumara — COMMENTED** [review]
Approved

**Comment by harshadilupkumara** [comment]
I have reviewed the changes, please ask Chealaka to merge the changes to
the master branch
Thank You
Harsha

**Review by harshadilupkumara — APPROVED** [review]
Approved

**Comment by harshadilupkumara** [comment]
@NiharikaGavvala 
I have reviewed the changes, please ask Chealaka to merge the changes to
the master branch

**Comment by NiharikaGavvala** [comment]
@ChelakaFernando harsha has approved and now you can merge

**Comment by ChelakaFernando** [comment]
LMS-BHC-PR-10-Updated the Return method according to code style guidelines in Book.java

**Pull request merged**
