### PR TITLE
LMS-BHC-PR-41-Added the author name comment for necessary changes Member.java

### PR DESCRIPTION
**Pull request by ChelakaFernando**
LMS-BHC-PR-41-Added the author name comment for necessary changes Member.java

### CODE REVIEW

**Comment by ChelakaFernando** [comment]
@NiharikaGavvala Please ask Harsha to review.
Thanks

**Comment by NiharikaGavvala** [comment]
@harshadilupkumara can you please review the changes that are made by chelaka. Thanks.

**Review by harshadilupkumara — APPROVED** [review]
@NiharikaGavvala 
Approved
Aske @ChelakaFernando  to merge the changes to master

**Comment by NiharikaGavvala** [comment]
@ChelakaFernando can you please merge it as harsha as approved it.

**Comment by ChelakaFernando** [comment]
@NiharikaGavvala Please ask harsha to review the changes -added mediator names

**Comment by NiharikaGavvala** [comment]
@harshadilupkumara can you review the changes that are made by chelaka.

**Comment by harshadilupkumara** [comment]
@NiharikaGavvala 
Please review the changes

**Review by harshadilupkumara — APPROVED** [review]
@NiharikaGavvala 
Approved asked @ChelakaFernando to merge the changes to the master branch

**Comment by NiharikaGavvala** [comment]
@ChelakaFernando can you merge it to master as it is approved.

**Pull request merged**
