### PR TITLE
LMS-HDK-PR-53- I have done the changes on  updating runReturnBook method in ReturnBookUI class

### PR DESCRIPTION
**Pull request by harshadilupkumara**
@NiharikaGavvala 
I have done the changes on  updating runReturnBook method in ReturnBookUI class
Ask @ChelakaFernando do the review

### CODE REVIEW

**Comment by NiharikaGavvala** [comment]
@ChelakaFernando can you please review the changes done by harsha.

**Review by ChelakaFernando — APPROVED** [review]
Approved

**Comment by harshadilupkumara** [comment]
@NiharikaGavvala 
I have done some changes please ask @ChelakaFernando  to review the changes

**Comment by NiharikaGavvala** [comment]
@ChelakaFernando can you re review the changes please

**Review by ChelakaFernando — APPROVED** [review]
Approved

**Comment by NiharikaGavvala** [comment]
@harshadilupkumara it is approved. please merge.

**Pull request merged**
