### PR TITLE
LMS-HDK-PR-07 -Refactoring get Library member method and get books catalog method in Library class file

### PR DESCRIPTION
**Pull request by harshadilupkumara**
@NiharikaGavvala  I have refactored get Library member method and get books catalog  @method in Library class file,
Please ask Chelaka to review the changes.

### CODE REVIEW

**Comment by NiharikaGavvala** [comment]
@ChelakaFernando Harsha has approved now you can merge it.

**Comment by NiharikaGavvala** [comment]
@ChelakaFernando  Harsha has requested to review the library and get books method in the library class file. Please review it. Thanks.

**Review by ChelakaFernando — CHANGES_REQUESTED** [review]
Hi Harsha,

I found a semi colon missing in row number 123 and import collection missing.
Will you be able to do the necessary changes for these.
Thank you.

**Comment by ChelakaFernando** [comment]
Hi Niharika,
I did the review and I have requested to change some.Please ask to check with the review comments.
Thank you.Regards,Chelaka
    On Wednesday, August 19, 2020, 04:30:54 PM GMT+10, NiharikaGavvala <notifications@github.com> wrote:  
 
 


@ChelakaFernando Harsha has requested to review the library and get books method in the library class file. Please review it. Thanks.

**Comment by NiharikaGavvala** [comment]
@harshadilupkumara  Chelaka has reviewed the code and found that some changes are to be made. So can you please look after that and change them. Thank you.

**Comment by harshadilupkumara** [comment]
@ChelakaFernando Changes has been done, please review and approved it

**Comment by harshadilupkumara** [comment]
@NiharikaGavvala request changes have done, please review and approve it

**Comment by harshadilupkumara** [comment]
@NiharikaGavvala I have done the changes which are requested by Chelaka,
please asked to review and approve

**Review by ChelakaFernando — APPROVED** [review]
Approved.Ready to Merge.

**Pull request merged**
