### PR TITLE
LMS-HDK-PR-34-Refactoring displayOutPut and setUiState in BorrowBook…

### PR DESCRIPTION
**Pull request by harshadilupkumara**
@ChelakaFernando 
Please ask @NiharikaGavvala to review the changes

### CODE REVIEW

**Comment by ChelakaFernando** [comment]
@NiharikaGavvala please review.
thanks

**Review by NiharikaGavvala — APPROVED** [review]
@ChelakaFernando approved and ask harsha to merge it. Thank you.

**Comment by ChelakaFernando** [comment]
@harshadilupkumara ,
@NiharikaGavvala had approved it.You can merge now.
Thanks

**Comment by harshadilupkumara** [comment]
@ChelakaFernando 
I have added some changes, please ask @NiharikaGavvala  to check the changes

**Comment by ChelakaFernando** [comment]
@NiharikaGavvala Harsha had done some changes.its ready to review.
Thanks

**Review by NiharikaGavvala — APPROVED** [review]
@ChelakaFernando Approved. Ask harsha to merge it to the master.

**Comment by ChelakaFernando** [comment]
@harshadilupkumara Ready to merge

**Pull request merged**
