### PR TITLE
LMS-NG-PR-88-changed the enum and RetrunBookUi 

### PR DESCRIPTION
**Pull request by NiharikaGavvala**
@harshadilupkumara can you please ask chelaka to review it.

### CODE REVIEW

**Comment by harshadilupkumara** [comment]
@ChelakaFernando 
Please review the chagnes

**Review by ChelakaFernando — COMMENTED** [review]
public ReturnBookUI(returnBookControl control) please change it to public ReturnBookUI(ReturnBookControl control)

**Comment by harshadilupkumara** [comment]
@ChelakaFernando 
please review the changes

**Review by ChelakaFernando — APPROVED** [review]
Approved

**Comment by harshadilupkumara** [comment]
@NiharikaGavvala please merge the changes to the master

**Pull request merged**
