### PR TITLE
LMS-NG-PR-130-Refactored try class in main.java

### PR DESCRIPTION
**Pull request by NiharikaGavvala**
@harshadilupkumara can you please ask chelaka to review the changes that i have made in main.java.

### CODE REVIEW

**Comment by harshadilupkumara** [comment]
@ChelakaFernando 
please review the changes

**Review by ChelakaFernando — APPROVED** [review]
Approved.You can merge it.

**Comment by ChelakaFernando** [comment]
@harshadilupkumara please tell Niharika to merge.

**Comment by harshadilupkumara** [comment]
@NiharikaGavvala 
Approved please  merge the changes to the master branch

**Pull request merged**
