### PR TITLE
LMS-BHC-PR-11-Updated the Repair method according to code style guidelines in Book.java

### PR DESCRIPTION
**Pull request by ChelakaFernando**
LMS-BHC-PR-11-Updated the Repair method according to code style guidelines in Book.java

### CODE REVIEW

**Comment by ChelakaFernando** [comment]
Hi @NiharikaGavvala ,
Did changes :LMS-BHC-PR-11-Updated the Repair method according to code style guidelines in Book.java.
Its ready for review.
Thanks.

**Comment by NiharikaGavvala** [comment]
@harshadilupkumara Can you please review the changes madeby chelaka. Thanks.

**Review by harshadilupkumara — COMMENTED** [review]
@NiharikaGavvala Ask Chelaka to check the changes again align to the coding style guideline.

line 112 - Curly brackets should use (even there is a single statement of IF condition)
line 120 - Method name should be camel case
line 128 - Curly brackets should use (even there is a single statement of IF condition)

Please check the code style guideline document

**Comment by NiharikaGavvala** [comment]
@ChelakaFernando Can you please check below missing code styles that are to be fixed which are reviewed by harsha
line 112 - Curly brackets should use (even there is a single statement of IF condition)
line 120 - Method name should be camel case
line 128 - Curly brackets should use (even there is a single statement of IF condition)

Please check the code style guideline document

Thanks.

**Comment by ChelakaFernando** [comment]
@NiharikaGavvala I have updated the necessary changes.
Thanks.

**Review by harshadilupkumara — APPROVED** [review]
@NiharikaGavvala Approved asked chelaka to merge to master branch

**Comment by ChelakaFernando** [comment]
Refactored the method names according to code style guidelines

**Pull request merged**
